#!/usr/bin/env bash

NEW='tag:new and '
NOREAD='-unread -inbox'

## Lists
notmuch tag +troskos $NOREAD -- $NEW to:"ia_aragon@lists.riseup.net"
notmuch tag +troskos $NOREAD -- $NEW to:"info_ia_aragon@lists.riseup.net"
notmuch tag +troskos $NOREAD -- $NEW not tag:troskos and subject:"IA Aragón"
notmuch tag +troskos $NOREAD -- $NEW not tag:troskos and subject:"Anticapitalistas Aragón"
notmuch tag +com_vank        -- $NEW to:"comitatovanchiglia_operativi@googlegroups.com"
notmuch tag +gap_vank        -- $NEW to:"gap_comitatoquartierevanchiglia@googlegroups.com"
notmuch tag +com_vank        -- $NEW to:"comitatovanchiglia_news@googlegroups.com"
notmuch tag +alot            -- $NEW to:"alot@noreply.github.com"
notmuch tag +antifaboxe      -- $NEW to:"antifaboxe-list@csoaskatasuna.org"
notmuch tag +isi             -- $NEW from:"segreteria1@isi.it"

## Deleted drafts and sent mails
notmuch tag +deleted $NOREAD -- $NEW folder:Trash and not tag:deleted
notmuch tag +deleted $NOREAD -- $NEW folder:trash and not tag:deleted
notmuch tag +draft           -- $NEW folder:Drafts and not tag:draft
notmuch tag +draft           -- $NEW folder:drafts and not tag:draft
notmuch tag +sent            -- $NEW folder:Sent and not tag:sent
notmuch tag +sent            -- $NEW folder:sent and not tag:sent

## Send notification to OS
s=$(notmuch search --format=json tag:new AND tag:inbox | notify-mail); 
if [ "$s" != "" ];
then
    notify-send -u normal MAIL "$s"
fi

## update addressbook with new mails
#for file in $(notmuch search --output=files tag:new) ; do
#    cat $file | notmuch_abook update
#done

## clear the 'new' tag
notmuch tag -new -- tag:new
