#!/usr/bin/env bash

NEW='tag:new and '
NOREAD='-unread -inbox'


## Send notification to OS
~/.local/bin/carta notify

## clear the 'new' tag
afew --tag --new

pgrep astroid && astroid --stop-polling

# Update alot
killall -SIGUSR1 alot 2>/dev/null
pkill -SIGRTMIN+9 waybar
exit 0
