#!/usr/bin/env bash

# svn editor variable:
export SVN_EDITOR=/usr/bin/vim
# editor variable:
if hash nvim 2>/dev/null; then
    export EDITOR="nvim"
    export DIFFPROG="nvim -d"
elif hash vim 2>/dev/null; then
    export EDITOR='vim'
    export DIFFPROG="vimdiff"
fi
export BROWSER=firefox
# add to PATH .local/bin and subdirectories
export PATH=$PATH:$(find -L ~/.local/bin -type d | tr '\n' ':' | sed 's/:$//'):~/go/bin
# nice java fonts
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

PERL_MB_OPT="--install_base \"$HOME/perl5\""
export PERL_MB_OPT
PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"
export PERL_MM_OPT

export GPG_TTY=$(tty)
export GPG_AGENT_INFO=$HOME/.gnupg/S.gpg-agent

# change look in qt5
export QT_QPA_PLATFORMTHEME="gtk2"
# export QT_STYLE_OVERRIDE=kvantum

# use wayland
# export MOZ_ENABLE_WAYLAND=1

# fzf should look also for hidden files
export FZF_DEFAULT_COMMAND="find . -path '*' ! -path '*.svn*' ! -path '*.git*' -type f"
