#!/usr/bin/env bash

# require trizen

echo -en "\x00prompt\x1fPACAUR GUI\n"

# if some value has been assigned to the variable $@ (array of parameters)
# if [ -v "$1" ]
# then
#     echo -en "\0message\x1fInput search term\n"
#     exit 1
# fi

INPUT=$1

case "${INPUT}" in
  "")
    echo -en "\0message\x1fInput search term\n"
    ;;
  \[*)
    PK=$(echo ${INPUT} | cut -d\  -f2 | sed "s/<\/*[a-z]\+>//g")
    trizen --color=never -Si "${PK}"
    ;;
  URL*)
    URL=$(echo ${INPUT} | cut -d\  -f3)
    xdg-open ${URL}
    ;;
  AUR*)
    URL=$(echo ${INPUT} | cut -d\  -f4)
    xdg-open ${URL}
    ;;
  *)
    echo -en "\0markup-rows\x1ftrue\n"
    trizen --color=never -Ss ${INPUT} |\
      sed "N;s/\n/ /" |\
      sed -e "s/^\([a-z]*\)\/\([^ ]*\)/[\1] <i>\2<\/i>\t/" \
        -e "s/\[installed\]/<b>INSTALLED<\/b>/" \
        -e "s/ \+/ /g"
    ;;
esac
