#!/usr/bin/env bash

# get the store
passdir=${PASSWORD_STORE_DIR:-$HOME"/.password-store"}
# run the menu
menu=$(find -L $passdir -name "*.gpg" -printf "%P\n" | sed -e 's/\.gpg$//')
choice=$(echo "$menu" |\
  rofi -dmenu -i -p 'Password Store: '\
  -mesg "Alt-s to show data"\
  -kb-custom-1 "Alt+s"\
  -markup-rows -theme-str '* { green:@red; lightgreen:@lightred; }'\
  )

exitcode=$?
echo $exitcode

# if NO choice exit graciously
[[ ${choice} == '' ]] && exit 0

# save to clipboard
pass show --clip ${choice} &> /dev/null
# notify
notify-send --urgency=critical\
    --app-name=rofi-pass\
    --icon=lock\
    'Password Store'\
    "secret copied to clipboard\n<small>(will be cleared in 45 sec.)</small>"

if [[ "${exitcode}" == 10 ]];
then
    data="$(pass ${choice} | sed 1d)"
    rofi -e "$data"
fi
#vim ft:sh
