#!/usr/bin/env bash

CMD=`basename $0`
PKG=$1
PKG_CACHE=${XDG_CACHE_HOME:-${HOME}/.cache}/texdoc
mkdir -p ${PKG_CACHE}

HELP="<i>I'll try to get the manual of your LaTeX package</i>"

PKG=$(ls -1 ${PKG_CACHE} | sed -e 's/\.pdf$//' | rofi -dmenu -p 'LaTeX PKG:' -mesg "${HELP}" -i)

[[ ${PKG} == '' ]] && exit 0

PKG_FILE=${PKG_CACHE}/${PKG}.pdf

if [[ -e ${PKG_FILE} ]];
then
  xdg-open ${PKG_FILE} &
else
  wget -O ${PKG_FILE} "http://texdoc.net/pkg/${PKG}"
  xdg-open ${PKG_FILE} &
fi
