#!/usr/bin/env bash
# this file autostart stuff


# early apps

# set background image:
background &
# start urxvt daemon
urxvtd -q -f -o &
# automatically turn on attached displays
srandrd ${HOME}/.local/bin/scripts/diplay-on

if [[ ${XDG_CURRENT_DESKTOP} == 'openbox' ]];
then
  # start panel
  tint2 -c ~/.config/tint2/sottone.tint2rc &

  #lal & # clock in tray
  lal -c green -f "%a %d-%m" &
  lal -c green -f "%H:%M" &

  # start a docking application (system Tray)
  docker-tray &
fi

sleep 10


# tray icons and applets

# automount devices
udiskie --use-udisks2 --tray &
# start the screen locker
xautolock -time 10 -locker "~/.local/bin/scripts/screenlock" &
# hide mouse if not in use
unclutter -root -visible &

# Machine specific start apps
case ${HOSTNAME} in
  'arcinghio')
    # battery tray icon
    xgamma -quiet -rgamma 1.11 -ggamma 1.01 -bgamma 0.93 &
    ;;
  'spin')
    echo RELOADAGENT | gpg-connect-agent
    dropbox-cli start
    pidgin &
    # volume control on panel
    volumeicon &
    ;;
esac

# launcher
synapse -s
