#!/usr/bin/env bash
# this file autostart stuff


# early apps

# set background image (the bg is set by display-on):
# ${HOME}/.local/bin/scripts/background &
# start urxvt daemon
urxvtd -q -f -o &
# automatically turn on attached displays
srandrd ${HOME}/.local/bin/scripts/display-on
${HOME}/.local/bin/scripts/display-on
compton -b


case ${XDG_CURRENT_DESKTOP} in
  'openbox')
    # start panel
    tint2 -c ~/.config/tint2/sottone.tint2rc &
  
    #lal & # clock in tray
    lal -c green -f "%a %d-%m" &
    lal -c green -f "%H:%M" &

    # start a docking application (system Tray)
    docker-tray &
    ;;
  'i3')
    i3-msg reload
    ;;
esac

sleep 10


# tray icons and applets

# automount devices
udiskie --use-udisks2 --tray &
# start the screen locker
xautolock -time 10 -notify 30\
  -notifier "notify-send XAUTOLOCK 'Screen locking in 30 secondsi'"\
  -locker "~/.local/bin/scripts/background --lock" &
# hide mouse if not in use
unclutter -root -visible &
# volume control on panel
volumeicon &

# Machine specific start apps
case ${HOSTNAME} in
  'arcinghio')
    # battery tray icon
    xgamma -quiet -rgamma 1.11 -ggamma 1.01 -bgamma 0.93 &
    ;;
  'spin')
    echo RELOADAGENT | gpg-connect-agent
    dropbox-cli start
    pidgin &
    ;;
  'dingo')
    nm-applet &
    pidgin &
    albert &
esac

# launcher
# synapse -s
