#!/usr/bin/env bash
# based on: https://github.com/cdown/passmenu

shopt -s nullglob globstar

nb='#111111'
nf='#777777'
sb='#111111'
sf='#903030'
font='-*-bitstream vera sans-medium-r-normal-*-*-*-*-*-*-*-iso8859-1'
font="-*-dejavu sans-medium-R-normal-*-*-*-*-*-*-*-iso10646-1"
dmenucmd=( dmenu -i -fn "$font" -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" )

prefix=${PASSWORD_STORE_DIR:-~/.password-store}
files=( "$prefix"/**/*.gpg )
files=( "${files[@]#"$prefix"/}" )
files=( "${files[@]%.gpg}" )
fbase=( "${files[@]##*/}" )

word=$(printf '%s\n' "${fbase[@]}" | "${dmenucmd[@]}" -p PASS: "$@")

if [[ -n $word ]]; then
  for match in "${files[@]}"; do  
    if [[ $word == ${match#*/} ]]; then
      /usr/bin/pass show -c "$match" #2>/dev/null
    fi  
  done
fi

