#!/usr/bin/env bash

TAGS='tag:deleted OR tag:killed'

echo '+++ DELETE KILLED MAIL +++'
files=$(notmuch search --output=files "$TAGS")

if [[ $files != '' ]]
then 
  notmuch search "$TAGS" | cut -c-$(tput cols)
  
  read -p '+++ Remove All deleted mails permanently?[y/n] +++  ' -n 1 -r
  echo

  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "$files" | xargs -L 1 -d '\n' rm
    echo '+++ Updating database +++'
    notmuch new --no-hooks
    echo '+++ Empty mail trash +++'
  fi
  
else
  echo '+++ No mails to delete +++'
fi


