#!/usr/bin/env zsh

TMP_FILE=$(mktemp --tmpdir offlineimap-XXXXXX.tmp)
offlineimap -l $TMP_FILE 2>/dev/null

new_mails=$(grep -s Copy $TMP_FILE | wc -l)
del_mails=$(grep -s Deleting $TMP_FILE | wc -l)
rm -f i$TMP_FILE

message=""
if [[ ! $new_mails == "0" ]];
then
  message="$message  New mails: $new_mails"
fi
if [[ ! $del_mails == "0" ]];
then
  message="$message Removed mails: $del_mails"
fi

if [[ ! $message == "" ]];
then
  notify-send "$message"
fi

notmuch new
