#!/usr/bin/env zsh

#echo 'Getting Mails (offlineimap)'

TMP_FILE=$(mktemp --tmpdir offlineimap-XXXXXX.tmp)
#offlineimap -o -u quiet >/dev/null 2>/dev/null
notmuch new >$TMP_FILE 2>/dev/null

message=$(sed -e 's/\. /.\n/g' $TMP_FILE | grep -e "Added\|Removed" | awk 'BEGIN{ORS=". "}{print $1,$2}')

rm $TMP_FILE

#del_mails=$(sed -e 's/\. /.\n/g' $TMP_FILE | grep -s Removed | awk '{print $2}')
#
#message=""
#if [[ ! $new_mails == "" ]];
#then
#  message="$message  New mails: $new_mails"
#fi
#if [[ ! $del_mails == "" ]];
#then
#  message="$message Removed mails: $del_mails"
#fi

if [[ ! $message == "" ]];
then
  notify-send  -i "mutt" -t 1000 --hint=int:transient:1 "MAIL:" "$message"
fi

