#!/usr/bin/env bash

INPUT=$1
OPENWITH=zathura
MPOPTIONS="-P A4 -F Helvetica -2 -p -"
TMPPDF=$(mktemp --tmpdir mutt-XXXXXX.pdf)

muttprint $MPOPTIONS | ps2pdf - $TMPPDF >/dev/null
zathura $TMPPDF >/dev/null & 

