#!/usr/bin/env bash

# Get input file name
INFILE=$1
INEXT=$(echo $INFILE | awk -F\. '{print $NF}')

# Get file type
MIME=$2

# Copy to temporary directory
TMPFILE=$(mktemp --tmpdir attach-XXXXX.$INEXT)
cp $INFILE $TMPFILE

# function to try several programs
function try {
  for app in "$@";
  do
    $app $TMPFILE > /dev/null 2>&1 && break
  done
}



# Open tmp file
case "$MIME" in
  "pdf")
    try zathura evince &
    ;;
  "image")
    try feh geeqie eog &
    ;;
  "spreadsheet")
    try gnumeric libreoffice &
    ;;
  "word")
    try abiword libreoffice &
    ;;
  "zip")
    try file-roller 'unzip -l' &
    ;;
  "gzip")
    try file-roller 'gunzip -l' &
    ;;
  "tar")
    try file-roller 'tar tvf' &
    ;;
esac

sleep 3
