#!/usr/bin/env sh
# end a command with ; to run in a terminal

SB="#c22"
SF="#6ff"
NB="#666"
NF="#6ff"
#FN="-*-fixed-medium-r-semicondensed-*-20-*-*-*-*-*-iso10646-*"
#FN="Droid Sans Mono-9"
FN="-*-dejavu sans mono-medium-r-normal--*-100-*-*-*-*-iso10646-1"
OPTIONS="-fn $FN -nb $NB -nf $NF -sb $SB -sf $SF -i"

DMENU="dmenu $OPTIONS"
TERMI="st -e"
CACHE="$HOME/.dmenu_cache_recent"

touch $CACHE
MOST_USED=`sort $CACHE | uniq -c | sort -r | colrm 1 8`
RUN=`(echo "$MOST_USED"; dmenu_path | grep -vxF "$MOST_USED") | $DMENU $@` &&
  (echo $RUN; head -n 99 $CACHE) > $CACHE.$$ &&
mv $CACHE.$$ $CACHE

case $RUN in
    *\;) exec `echo $TERMI $RUN | sed -e 's/;$//'`;;
    *)   exec $RUN;;
esac
