#!/usr/bin/env bash
# this take slides in ps and put them (2 per page) in a a4paper in pdf format
# usage:
#     slides4print infile.ps [outfile.pdf]

IN=$1
OUT=$2

if [[ $OUT == '' ]];
then
  OUT=${IN/.ps/}-A4.pdf
fi

psnup -f -2 -s1.4 $IN /tmp/tmp.ps
ps2pdf /tmp/tmp.ps $OUT

echo Output in $OUT
