directory: ~/muzik
library: ~/docus/muziklib.db
per_disc_numbering: yes

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
    '\s': _

asciify_paths: yes
plugins:
    - fromfilename
    - edit
    - fetchart
    - replaygain
    - thumbnails
    - missing
    - zero

zero:
    fields: month day genre comments
    comments: [EAC, LAME, from.+collection, 'ripped by']
    update_database: true

replaygain:
    backend: command

import:
    move: yes
    copy: yes
    write: yes

paths:
    default: $albumartist/${year}_$album%aunique{}/${disc}-${track}_$title
    singleton: Non-Album/$artist/$title
    comp: Various/${year}_$album%aunique{}/${disc}-${track}_$title

