#!/usr/bin/env bash
# this file autostart stuff

# automatically turn on attached displays
srandrd ${HOME}/.local/bin/display-on &
${HOME}/.local/bin/display-on &
compton -b &

syndaemon -d -i 0.3 -K -R
sleep 5

# tray icons and applets

# automount devices
udiskie --use-udisks2 --tray &
# start the screen locker
xautolock -time 10 -notify 30\
  -notifier "notify-send --icon=lock --app-name=screensaver XAUTOLOCK 'Screen locking in 30 seconds'"\
  -locker "~/.local/bin/background --lock" &
# hide mouse if not in use
unclutter -root -visible &

# start xdg autostat apps
dex -a -e i3wm

# ~/.i3/volume_bar.py | xob 2>>1 1>>/dev/null &
