#!/usr/bin/env bash
# this file autostart stuff


# early apps

# automatically turn on attached displays
srandrd ${HOME}/.local/bin/display-on &
${HOME}/.local/bin/display-on &
compton -b &


case ${XDG_CURRENT_DESKTOP} in
  'openbox')
    # start panel
    tint2 -c ~/.config/tint2/sottone.tint2rc &
  
    #lal & # clock in tray
    lal -c green -f "%a %d-%m" &
    lal -c green -f "%H:%M" &

    # start a docking application (system Tray)
    docker-tray &
    ;;
  'i3')
    # i3-msg reload
    ;;
esac

sleep 5


# tray icons and applets

# automount devices
udiskie --use-udisks2 --tray &
# start the screen locker
xautolock -time 10 -notify 30\
  -notifier "notify-send XAUTOLOCK 'Screen locking in 30 secondsi'"\
  -locker "~/.local/bin/background --lock" &
# hide mouse if not in use
unclutter -root -visible &
# volume control on panel
# volumeicon &

# Machine specific start apps
case ${HOSTNAME} in
  'arcinghio')
    # battery tray icon
    xgamma -quiet -rgamma 1.11 -ggamma 1.01 -bgamma 0.93 &
    ;;
  'spin')
    dropbox-cli start
    # pidgin &
    ;;
  'dingo'|'susto')
    nm-applet &
    # cmst &
    # /usr/bin/env albert &
    blueman-applet &
    # QSyncthingTray &
    kalu &
    riot-desktop --hidden &
esac
